package dsw.gerudok.app.gui.swing.error;

public enum ErrorType {
    PRAZAN_PASTE,WORKSPACE_DELETE, DELETE_PRAZNO, DODAVANJE_SLOTA, PRAZAN_RENAME, NESELEKTOVAN_PAGE, COPY_PROJEKAT, COPY_SLOT, COPY_PAGE, COPY_WORKSPACE,NESELEKTOVAN_SLOT,VISE_SELEKTOVANI_SLOTOVI,PRAZNI_TEXT_U_SLOTU
}
